### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by derkrankesenator** [NiceneNerd/Wild-Bits#29]
Everytime I try to start wildbits it's fully white.
I get this output:
[pywebview] Using Cocoa
Bottle v0.13.2 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:5707/
Hit Ctrl-C to quit.

127.0.0.1 - - [24/Nov/2024 17:59:54] "GET /index.html HTTP/1.1" 200 337
2024-11-24 17:59:54.335 Python[5161:95911] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-24 17:59:54.335 Python[5161:95911] +[IMKInputSession subclass]: chose IMKInputSession_Modern
127.0.0.1 - - [24/Nov/2024 18:00:01] "GET /scripts/bundle.js HTTP/1.1" 404 739
[pywebview] Main window failed to start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/util.py", line 181, in inject_pywebview
    func_list = generate_func()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/util.py", line 169, in generate_func
    functions = get_functions(window._js_api)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/util.py", line 164, in get_functions
    get_functions(attr, full_name, functions)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/util.py", line 164, in get_functions
    get_functions(attr, full_name, functions)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/util.py", line 159, in get_functions
    attr = getattr(obj, name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/dom/dom.py", line 18, in body
    return self._elements.get('body', Element(self.__window, 'body'))
                                      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/dom/element.py", line 77, in __init__
    self.__generate_events()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/dom/element.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/dom/element.py", line 419, in __generate_events
    events = self._window.evaluate_js(f"""
        {self._query_command};
    ...<12 lines>...
            .map(function(f) {{ return f.substr(2) }});
    """)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/webview/window.py", line 43, in wrapper
    raise WebViewException('Main window failed to start')
webview.errors.WebViewException: Main window failed to start


I'm using macos.

**Comment by derkrankesenator** [comment]
take the release not the python one
