### ISSUE TITLE
[Windows] Not launching

### ISSUE THREAD

**Issue by roobscoob** [NiceneNerd/Wild-Bits#4]
Command: `py -m wildbits`
Result: 
```
Unhandled Exception: Python.Runtime.PythonException: Exception : Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at Windows.Web.UI.Interop.WebViewControl.Navigate(Uri source)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlHost.Navigate(Uri source)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Navigate(String source)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by NiceneNerd** [comment]
Try installing CEF: `pip install cefpython3`
