### ISSUE TITLE
Exception: Python version not supported: 3.8.5

### ISSUE THREAD

**Issue by jordanbtucker** [NiceneNerd/Wild-Bits#6]
```
PS D:\Users\Jordan\Desktop> python -m wildbits
Traceback (most recent call last):
  File "C:\Users\Jordan\scoop\apps\python\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jordan\scoop\apps\python\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jordan\scoop\apps\python\current\lib\site-packages\wildbits\__main__.py", line 385, in <module>
    main()
  File "C:\Users\Jordan\scoop\apps\python\current\lib\site-packages\wildbits\__main__.py", line 366, in main
    from cefpython3 import cefpython
  File "C:\Users\Jordan\scoop\apps\python\current\lib\site-packages\cefpython3\__init__.py", line 64, in <module>
    raise Exception("Python version not supported: " + sys.version)
Exception: Python version not supported: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
```

**Comment by NiceneNerd** [comment]
Yeah, on Windows you won't be able to use Wild Bits with Python 3.8 until cefpython3 adds support for it.
